Repository Bibliko/Stock_Project, pull requests merged in 2020-07, with the labels that each got.

#27 Many updates for Forgot Password
  back-end/index.js
  back-end/package-lock.json
  back-end/package.json
  back-end/passport/strategies/signup.js
  back-end/verificationHTML/verifyEmail.html
  back-end/verificationHTML/verifyPassword.html
  front-end/src/components/TextField/normalTextField.js
  front-end/src/components/TextField/passwordTextField.js
  front-end/src/pages/Login/ForgotPassword.js
  front-end/src/pages/Login/Verification/Fail.js
  front-end/src/pages/Login/Verification/Succeed.js
Labels: enhancement

#28 Change Login UI
  front-end/src/pages/Login/Login.js
Labels: bug, enhancement

#29 Minor changes in Login UI
  front-end/src/pages/Login/Login.js
Labels: bug

#30 Update schema.prisma
  back-end/prisma/schema.prisma
Labels: enhancement

#31 Landing Page front-end
  back-end/prisma/schema.prisma
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/components/Layout/AppBar.js
  front-end/src/components/Layout/Drawer.js
  front-end/src/components/Layout/Layout.js
  front-end/src/pages/Login/Login.js
  front-end/src/pages/Main/LandingPage.js
Labels: enhancement

#32 Change avatar size
  back-end/passport/strategies/facebook.js
  front-end/src/components/Layout/AppBar.js
Labels: bug, enhancement

#33 Super minor change
  front-end/src/components/Layout/AppBar.js
  front-end/src/components/Layout/Layout.js
Labels: bug

#34 Minor change again
  front-end/src/components/Layout/AppBar.js
  front-end/src/components/Layout/Layout.js
Labels: bug

#36 Re-factor FunctionsProvider file
  front-end/src/App.js
  front-end/src/components/Layout/AppBar.js
  front-end/src/components/Layout/Layout.js
  front-end/src/pages/Login/ForgotPassword.js
  front-end/src/pages/Login/Login.js
  front-end/src/pages/Login/Signup.js
  front-end/src/pages/Login/Verification/Fail.js
  front-end/src/pages/Login/Verification/Succeed.js
  front-end/src/pages/Main/AccountSummary.js
  front-end/src/pages/Main/LandingPage.js
  front-end/src/provider/FunctionsProvider.js
  front-end/src/utils/UserUtil.js
Labels: enhancement

#37 Re Factor back-end code
  back-end/index.js
  back-end/utils/DayTimeUtil.js
  back-end/utils/SocketUtil.js
  back-end/utils/UserUtil.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/pages/Main/AccountSummary.js
Labels: enhancement

#38 npm update
  back-end/package-lock.json
  back-end/package.json
  front-end/package-lock.json
  front-end/package.json
Labels: enhancement

#40 Account Summary Updates
  back-end/algolia/algoliaIndices.js
  back-end/index.js
  back-end/package-lock.json
  back-end/package.json
  back-end/prisma/schema.prisma
  back-end/routes/user.js
  back-end/utils/FinancialModelingPrepUtil.js
  back-end/utils/SocketUtil.js
  front-end/src/App.js
  front-end/src/pages/Main/AccountSummary.js
  front-end/src/pages/Main/LandingPage.js
  front-end/src/redux/storeReducers/user.reducer.js
  front-end/src/utils/SocketUtil.js
  front-end/src/utils/UserUtil.js
Labels: enhancement

#43 Account Summary Redboard in Figma Design
  back-end/index.js
  back-end/prisma/schema.prisma
  back-end/routes/marketHolidays.js
  back-end/utils/DayTimeUtil.js
  back-end/utils/FinancialModelingPrepUtil.js
  back-end/utils/MarketHolidaysUtil.js
  back-end/utils/SocketUtil.js
  back-end/utils/UserUtil.js
  front-end/package-lock.json
  front-end/src/App.js
  front-end/src/components/Layout/Layout.js
  front-end/src/pages/Main/AccountSummary.js
  front-end/src/pages/Main/LandingPage.js
  front-end/src/redux/storeActions/actionTypes.js
  front-end/src/redux/storeActions/actions.js
  front-end/src/redux/storeReducer.js
  front-end/src/redux/storeReducers/market.reducer.js
  front-end/src/redux/storeReducers/user.reducer.js
  front-end/src/utils/DayTimeUtil.js
  front-end/src/utils/SocketUtil.js
  front-end/src/utils/UserUtil.js
Labels: enhancement

#46 Add close button to Reminder Component
  front-end/src/components/Layout/Layout.js
  front-end/src/components/Reminder/Reminder.js
  front-end/src/utils/NetworkUtil.js
Labels: enhancement

#47 Unfinished Account Summary Chart + check Config and .Env automatically
  back-end/checkConfigFolder.js
  back-end/package-lock.json
  back-end/package.json
  back-end/queries/createModels.js
  front-end/checkEnvFile.js
  front-end/firebase/firebaseStorage.js
  front-end/package-lock.json
  front-end/package.json
  front-end/public/Bibliko.png
  front-end/src/components/Chart/AccountSummaryChart.js
  front-end/src/components/Layout/AppBar.js
  front-end/src/pages/Main/AccountSummary.js
  front-end/src/theme/ThemeUtil.js
Labels: enhancement

#48 Finished Portfolio Chart
  back-end/prisma/schema.prisma
  back-end/utils/DayTimeUtil.js
  back-end/utils/SocketUtil.js
  back-end/utils/UserUtil.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Chart/AccountSummaryChart.js
  front-end/src/components/Layout/AppBar.js
  front-end/src/components/Layout/Layout.js
  front-end/src/components/Table/AccountSummaryTable/HoldingsTableRow.js
  front-end/src/components/Table/AccountSummaryTable/SummaryTableContainer.js
  front-end/src/pages/Main/AccountSummary.js
  front-end/src/utils/BrowserUtil.js
  front-end/src/utils/DayTimeUtil.js
  front-end/src/utils/NumberUtil.js
Labels: enhancement

#49 Add border to Account Summary Table
  back-end/utils/UserUtil.js
  front-end/src/components/Chart/AccountSummaryChart.js
  front-end/src/components/Layout/Layout.js
  front-end/src/components/Table/AccountSummaryTable/HoldingsTableContainer.js
  front-end/src/components/Table/AccountSummaryTable/HoldingsTableRow.js
  front-end/src/components/Table/AccountSummaryTable/SummaryTableContainer.js
  front-end/src/pages/Main/AccountSummary.js
  front-end/src/utils/DayTimeUtil.js
Labels: enhancement

#51 Add basic supports for Code formatting and Flow Types
  .vscode/settings.json
  back-end/.babelrc
  back-end/.eslintignore
  back-end/.eslintrc
  back-end/.flowconfig
  back-end/.gitignore
  back-end/.prettierignore
  back-end/.prettierrc
  back-end/algolia/algoliaIndices.js
  back-end/bin/PrismaFlowTypedGenerator/ModelTypeDefExtractor.js
  back-end/bin/PrismaFlowTypedGenerator/index.js
  back-end/checkChangesInSchemaPrisma.js
  back-end/checkConfigFolder.js
  back-end/displayNpmHelp.js
  back-end/firebase/firebaseStorage.js
  back-end/herokuUpdateDb.js
  back-end/index.js
  back-end/package-lock.json
  back-end/package.json
  back-end/passport/index.js
  back-end/passport/strategies/facebook.js
  back-end/passport/strategies/google.js
  back-end/passport/strategies/login.js
  back-end/passport/strategies/signup.js
  back-end/redis/redis-client.js
  back-end/redis/testRedis.js
  back-end/routes/marketHolidays.js
  back-end/routes/redis.js
  back-end/routes/share.js
  back-end/routes/user.js
  back-end/utils/DayTimeUtil.js
  back-end/utils/FinancialModelingPrepUtil.js
  back-end/utils/MarketHolidaysUtil.js
  back-end/utils/NetworkUtil.js
  back-end/utils/SocketUtil.js
  back-end/utils/UserUtil.js
Labels: enhancement
